version: "3"

services:
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./packages/dashboard/Dockerfile
      args:
        - VITE_API_URL=http://127.0.0.1:52001
    restart: always
    ports:
      - 127.0.0.1:52000:8080

  api:
    container_name: api
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:52001:8080
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379

  artisan:
    container_name: artisan
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./packages/artisan/Dockerfile
    restart: always
    environment:
      S3_ENDPOINT: https://ams3.digitaloceanspaces.com
      S3_REGION: eu-west-1
      S3_ACCESS_KEY: DO00883BLC28ZK29PL23
      S3_SECRET_KEY: il6SJF8F3BebdDn1PkEmhGRL/5W5UnrcqFhUSX2W3iQ
      S3_BUCKET: streamer
      REDIS_HOST: redis
      REDIS_PORT: 6379

  stitcher:
    container_name: stitcher
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./packages/stitcher/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:52002:8080
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      S3_PUBLIC_URL: https://streamer.ams3.cdn.digitaloceanspaces.com

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
